// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddPostInput struct {
	Content string `json:"content"`
}

type AuthOutput struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type DeletePostInput struct {
	PostID string `json:"postId"`
}

type EditPostInput struct {
	PostID  string `json:"postId"`
	Content string `json:"content"`
}

type GetPostInput struct {
	PostID string `json:"postId"`
}

type GetPostsByUsernameInput struct {
	Username string `json:"username"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID        string     `json:"id"`
	Content   string     `json:"content"`
	Link      string     `json:"link"`
	User      *User      `json:"user"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}

type RegisterInput struct {
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string     `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Fullname  *string    `json:"fullname"`
	Bio       *string    `json:"bio"`
	Admin     bool       `json:"admin"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}
